### ISSUE TITLE
Compile problem on Windows

### ISSUE THREAD

**Issue by llamafilm** [CESNET/UltraGrid#113]
I tried to compile from git master on Windows 2016, and I ended up with a binary that works in MSYS2, but it doesn't work in CMD or Powershell.  There it just exits with no output even with `--verbose=7`
This is my first time ever compiling anything on Windows so I'm probably missing something obvious.  I had to learn a lot of new tools to follow the guide on the Wiki.  Here's what I did:

- Install MSYS2 and run the rest of the steps inside that shell
- `cd UltraGrid-master`
-  Run `prepare_msys.sh`
- This script installed a bunch of things and then it failed at line 64 because I did not install live555.  I think the rest is optional
- `pacman -Sy autoconf automake make mingw-w64-x86_64-toolchain pkg-config`
- `./autogen.sh --enable-ndi`
- `make`

What do I need to do to get a portable binary that will run in CMD or Powershell?

**Comment by llamafilm** [comment]
I also tried compiling in the mingw64.exe shell but I still have the same problem.

**Comment by MartinPulec** [comment]
There is a problem with Powershell that it doesn't report missing DLLs - I didn't find out how to workaround that - when running under cmd.exe, the window pop ups but nut under Powershell.

Anyways, I think that it is most likely caused by missing DLLs that are in PATH within MSYS but not if run from PowerShell, please look at [this page](https://github.com/CESNET/UltraGrid/wiki/Compile-UltraGrid-(Source)#bundling-in-windows) (I've just now improved it).

**Comment by llamafilm** [comment]
I'm not sure what the mistake was exactly, but this is working now after starting over from scratch and learning more about MSYS.  The bundling script is helpful, thanks.  With that, it runs in both CMD and Powershell.
