### ISSUE TITLE
Please compile the AppImage with --enable-qt

### ISSUE THREAD

**Issue by probonopd** [CESNET/UltraGrid#12]
Please compile what goes into the AppImage with `--enable-qt` so that this error does not show up:

![](https://github.com/AppImage/appimage.github.io/blob/8aeadc3b5804cf0841c4f8429c14e73b0259706d/database/UltraGrid/screenshot.png?raw=true)

Thanks.

Reference:
https://github.com/AppImage/appimage.github.io/pull/867

**Comment by probonopd** [comment]
Ubuntu 14.04, full log here:
https://travis-ci.org/AppImage/appimage.github.io/builds/440301653#L641

**Comment by MartinPulec** [comment]
Ah, I see, thanks a lot. I'll take a look at it - actually I didn't check the image with 14.04 and I neither have a virtual machine so I'll see tomorrow or next week. The distro is unfortunately a bit old - hopefully it will work after some tweak.

However, unfortunately not all old, yet supported, distros will work with this image, either. At least CentOS 6 won't work because the image is currently built with CentOS 7. CentOS 6 ships ancient GCC (4.4) which won't compile UltraGrid. I am currently not sure if there can be compiled/installed a newer compiler while keeping the old glibc ABI.

**Comment by MartinPulec** [comment]
This particular bug shoud be fixed in current build - it was caused by loading MagickWand library in the AppImage bundle. Because the plugin requiring MagickWand is not really important, it is currently build without it.

**Comment by probonopd** [comment]
Thank you.
