### ISSUE TITLE
UltraGrid-1.5 appimage with AJA hardware on CentOS

### ISSUE THREAD

**Issue by unittech** [CESNET/UltraGrid#125]
I wasn't sure if this is the right place to ask but i wanted to know if AJA hardware is supported on the UltraGrid-1.5 appimage

We have a department of Autodesk Flame Systems which run on CentOS7

I can run the app image and AJA is a video source option but seems to only show bars and not the image sent from SDI 3 of the aja card

Thanks

**Comment by thpryrchn** [comment]
Try a newer version, or compile the latest source code.  1.5 is ancient history. That release is over 2 years old! Heck, there has been over 300 commits since 1.6 came out.  

If you want the latest build, get it from Continuous builds in the https://github.com/CESNET/UltraGrid/releases area. 

Some features are only available if you compile yourself. Like NDI, because of licensing issues.

**Comment by thpryrchn** [comment]
@unittech Did you ever try a newer release?

**Comment by alatteri** [comment]
UG can not tap the Flame output of the AJA in the way you are thinking.  You would have to loopback AJA SDI port 3 (flame out) into AJA SDI port 1 (input).  Not even sure that would work actually.  But you can't capture the AJA signal before it goes out the card from Flame.

**Comment by MartinPulec** [comment]
Yes, if you want to capture AJA SDI output, it is currently not possible, as @alatteri said. I've tried to talk to AJA if it can be supported but currently with no result. So I assume that it is currently not possible? (Or do anyone of you know a software that can do that for AJA?) I guess that the cards would be capable of doing that, but perhaps firmware doesn't support that.

@unittech the version 1.5 you are using because the later AppImages don't support CentOS 7? Well, I think that the current version may be compiled on CentOS 7. Possibly also AppImage with AJA could be prepared. But as Alan noted, it depends whether it would work for you or not.

**Comment by unittech** [comment]
So if i understand correctly, The AJA support is for the input ports not the output. 
Would a simple physical cable out of the sdi out, to the sdi in do the trick or am i mis understanding? 

If UltraGrid can't grab the sdi out or the sdi in? What are you able to use the AJA card for? 

sorry i'm a newbie! 

Thanks

**Comment by alatteri** [comment]
In theory that would work, but highly unlikely.  The AJA card can probably only be used by 1 app at a time, so Flame and UG probably couldn't have access simultaneously.

> So if i understand correctly, The AJA support is for the input ports not the output.
> Would a simple physical cable out of the sdi out, to the sdi in do the trick or am i mis understanding?
> 
> If UltraGrid can't grab the sdi out or the sdi in? What are you able to use the AJA card for?
> 
> sorry i'm a newbie!
> 
> Thanks

**Comment by MartinPulec** [comment]
Hi,

> So if i understand correctly, The AJA support is for the input ports not the output.

both, but input ports are supposed to be captured and output written, not vice versa.

> Would a simple physical cable out of the sdi out, to the sdi in do the trick or am i mis understanding?

I think it would. The only thing that may need to be solved is the internal routing. I don't know how Flame, UltraGrid routes only the necessary paths. But as 2 applications are touching the same card in possibly conflicting way, you may want to check the signal routes inside the Cables AJA application.

I cannot tell that it would work right now but if you'd paste how Flame routes the output signal we can look (and possibly UltraGrid routing may be modified if there would be conflicting paths).

**Comment by MartinPulec** [comment]
Any update on that? I'd perhaps close this issue because the issue took 2 paths making it harder to keep track – UG 1.5 support and AJA routing problem.
