### ISSUE TITLE
HDR Metadata over HDMI

### ISSUE THREAD

**Issue by garcurr** [CESNET/UltraGrid#131]
Hi All

Having followed a previous thread started by alatteri I am trying without success
to get the HDR metadata over HDMI from a Decklink (4K Extreme 12G) to work.

I'm running 
UltraGrid 1.6+ (tags/continuous rev 73d4a5b1 built Feb 10 2021 14:59:38) 

I've tried an LG, Sony and Panasonic TV. But with all available options ./uv -d decklink:HDR=PQ, =HLG etc 
the TV's stay in SDR and do no switch to the flagged HDR mode.
I've tried rolling back BMD drivers to 11.6 but that hasn't made any difference.

Any help would be greatly appreciated.
Thanks
Gary

**Comment by MartinPulec** [comment]
Hi Gary,

just FYI, it is also possible in UltraGrid to use numbers _0-7_ (should be indices of transfer functions as per CEA 861). 

UltraGrid tries to mimic the behavior of `SignalGenHDR` example from _BlackMagic DeckLink SDK_. Would you be able to compile and run it to check whether you can find a suitable parameters there? If you give me your platform, I may perhaps compile it for you.

**Comment by garcurr** [comment]
Hi Martin

I did try 0-7 without success.
If I run  ./uv -d decklink:hdr=help I do see the HDR parameters are available for the card, I think.
I'm a bit new to compiling so will give it a go but if you were able to compile that would be great.
I'm on a Mac Pro (2019) Catalina 10.15.3.

Many Thanks
Gary

**Comment by MartinPulec** [comment]
Hi Gary,

> If I run ./uv -d decklink:hdr=help I do see the HDR parameters are available for the card, I think.

Not really - it is not taken from the card. I think that if the card supports HDR, it can output arbitrary HDR metadata.

> I'm a bit new to compiling so will give it a go but if you were able to compile that would be great.
> I'm on a Mac Pro (2019) Catalina 10.15.3.

Fortunately notably for macOS there are precompiled binaries in the SDK - if you unzip the SDK, there is an image in the SDK root directory - _Mac/Samples/Binaries.dmg_. If you mount and open it, there are bunch of apps, but notably _SignalGenHDR_. I've tried and the application shows a window where there can be tweaked those HDR parameters (I could not have tested with a real DeckLink, since I have no attached, however).

Regards,
Martin

**Comment by garcurr** [comment]
Hi Martin. 

Tried SignalGenHDR, and it looks like the decklink card is older than I realised and doesn't
have HDMI 2.0a output. Getting hold of a newer Decklink. Thanks for your help.

Best
Gary

**Comment by MartinPulec** [comment]
Ok, thanks for the info, so I'd perhaps close it for now.

**Comment by garcurr** [comment]
Working with a Decklink 4k Mini Monitor.
Thanks
