### ISSUE TITLE
NDI: No data received

### ISSUE THREAD

**Issue by erichorwitz** [CESNET/UltraGrid#148]
Trying to use NDI source.

NDI connects to sender. Say receiving from source. Then says Status Changed. Then a repeating No Data Received message. I have tested with NDI Viewer and its working. SDK version 4.6. I pulled and built Ultragrid today.

uv -t ndi:url=10.5.25.51 -c libavcodec:encoder=hevc_nvenc:bitrate=10M -s embedded --audio-codec=AAC --audio-capture-format channels=2 -f rs:192:240 -f A:mult:2 --verbose -m 1200 10.5.25.2

**Comment by MartinPulec** [comment]
Hi Eric,

and does the UltraGrid receive the audio/video data or not at all? What is the characteristic of the source? The `NDIlib_frame_type_none` frame comes directly from the NDI API, I guess that after the timeout, which is set to 200 ms in UltraGrid for NDI. So my guess is that the message (isolated) is caused when no data arrives for 200 ms - which may be given by the source or something else (perhaps some performance issues?).

**Comment by MartinPulec** [comment]
closed for inactivity

**Comment by alatteri** [comment]
I am getting this too when testing with NDI.

administrator@:~$ uv -m 1416 -t ndi:extra_ips=192.168.1.104
UltraGrid 1.9+ (tags/continuous rev 1a71edf built Jun 24 2024 17:21:45)

Control socket listening on port 36963
[NDI cap.] Looking for source(s)...
[NDI cap.] Receiving from source: WS104 (Flame NDI Video), URL: 192.168.1.104:5961
[NDI cap.] Status changed!
[NDI cap.] No data received.
ExitLast message repeated 5 times

**Comment by MartinPulec** [comment]
Hi @alatteri,

> I am getting this too when testing with NDI.

is it supposed to be a bug report or just a FYI? If the first is the case, please open a new issue. The "No data received" message doesn't imply to me that the issue is necessarily the same, especially where there is no further info from the original reporter.

**Comment by alatteri** [comment]
OK...I'll gather more data and open a new issue.

Thanks.

**Comment by MartinPulec** [comment]
Just for the record, we've got similar report to this (getting `No data received.`) outside of GH so I've looked at it further and I've find out:

1. 16-bit YCbCr displayed in Windows did produce 'No data received.' (actually an issue of NDI, which told that stride doesn't need to be set, but it needs; but only for 16-bit and in Windows)
2. otherwise, all the remaining cases I got the message it was due to firewall - I've updated the [NDI wiki page](https://github.com/CESNET/UltraGrid/wiki/NDI#firewall). To sum up - it is usually needed to have a port **TCP/596X** opened on the _sender_ and the same port number at the **receiver** **but** using _UDP_. The ports used by NDI start with **5960** but the number may also increase, eg. when you restart the NDI sender (the actual number that will be used should be seen in `-t ndi:help` source listing). There is few minutes timeout before the lowest numbered index is reused so it is wise to allow at least few more ports (or you'll likely need to wait).
