### ISSUE TITLE
decklink missing on mac os 11.2.3

### ISSUE THREAD

**Issue by erichorwitz** [CESNET/UltraGrid#150]
decklink is missing on mac continuous build on mac 11.2.3. Desktop Video Drivers installed version 12.0. Running on M1 Mac mini.

**Comment by erichorwitz** [comment]
even tried back reving to 11.6 still missing decklink

**Comment by MartinPulec** [comment]
Hi, this is quite expected. I guess you are running it with Rosetta 2? I think it will be needed a native ARM build. However just for sure, I've tried create [a build with DeckLink SDK 12](https://github.com/CESNET/UltraGrid/actions/runs/704140895) - would you be able try this out if it accidentally won't help?

Regarding the ARM Mac build - UltraGrid should compile natively on M1 Mac. We are just waiting with the builds for the dependencies to be present, namely Qt (perhaps from Macports), in order to avoid custom build. However if you compile the application natively, I guess it should work with DeckLink.

**Comment by MartinPulec** [comment]
UPDATE: Ok ok, my fault, DeckLink has indeed disappeared from the build, I'll fix it ASAP.

**Comment by erichorwitz** [comment]
Great! please let me know once its rebuilt.

**Comment by MartinPulec** [comment]
The continuous build should have been rebuilt few seconds ago.

**Comment by erichorwitz** [comment]
is it the arm build or the regular mac one?

I tried the sdk12 build but that doesn't seem to have decklink either.....

**Comment by erichorwitz** [comment]
Can confirm that the MacOS continuous build now has decklink

**Comment by MartinPulec** [comment]
M1 is not yet ready - we may build it as soon as Qt is available via macports for arm64. Perhaps we may build a "headless" version if there will be some delay.

The updated version with sdk12 ([this run](https://github.com/CESNET/UltraGrid/actions/runs/705690211)) worked for me. However no obvious change against the _continuous_ one (I unfortunately do not have any DeckLink connected to the M1 MacBook).

**Comment by erichorwitz** [comment]
I have it working on an M1 mac on Big Sur 11.2.3 with Desktop Video 12.

Also Qt6 is available for arm. I have that working. Not sure there are conflicts with Qt5 in Ultragrid

**Comment by MartinPulec** [comment]
> I have it working on an M1 mac on Big Sur 11.2.3 with Desktop Video 12.

Thanks, good to know.

> Also Qt6 is available for arm. I have that working. Not sure there are conflicts with Qt5 in Ultragrid

That's true, I managed to install it. But there are currently multiple issues with using Qt6 on M1 Mac with UltraGrid (I've opened issue #152).

**Comment by MartinPulec** [comment]
Original issue seems to be solved. M1 build – we are not currently building it, UltraGrid is compatible with M1 macs at the source code level but native builds will be perhaps as soon as [GitHub provides native workers](https://github.com/github/roadmap/issues/528). Cross-compilation is possible but perhaps not worth doing since possibility to use native runners is just a matter of a time.
