### ISSUE TITLE
NV-Codec-Headers official Intra Refresh support?

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#174]
Hi,

Looks like nv-codec-headers for ffmpeg might finally officially support Intra Refresh which would be very beneficial.

https://github.com/FFmpeg/nv-codec-headers/commit/b641a195edbe3ac9788e681e22c2e2fad8aacddb

Wondering you could compile against this version?

Thanks,
Alan

**Comment by MartinPulec** [comment]
Hi, thanks for the info, do you have some more information what does the `singleSliceIntraRefresh` do?

Intra refresh per se is in theory supported for a longer time in the headers, but not entirely in a satisfactory manner - I mean mainly that IDR frame overrides all previous references resulting in a pulsating image.

Currently the master branch of the headers is taken for the UltraGrid AppImage build so there is no problem. But FFmpeg is patched by us to utilize the (former) intra-refresh option.

I don't currently have much time to test the change but I can at least enable it in the UG Linux continuous build if you wish and are able to test.

**Comment by alatteri** [comment]
Hi Martin,

I don't know what that parameter does.  I too am rather busy with a few projects, so I wouldn't be able to test for a few weeks.

Thanks. 
Alan

**Comment by MartinPulec** [comment]
Ok, no problem, I'll perhaps add it anyways and we will see if anyone will be able reasonably early test.

**Comment by alatteri** [comment]
Hi Martin,

This is what I found online.

https://github.com/FFmpeg/nv-codec-headers/blob/b641a195edbe3ac9788e681e22c2e2fad8aacddb/include/ffnvcodec/nvEncodeAPI.h#L1450

and also from NVENC API Guide:

```
The default NVENCODE API Intra Refresh behavior is slice based i.e frames in an intra refresh wave will have multiple slices with one slice containing only intra coded MBs / CTUs.

If the application does not explicitly specify the number of slices or if the specified number of slices are less than 3, during the intra refresh wave, the driver will set 3 slices per frame.
For NV_ENC_CONFIG_H264::sliceMode = 0 (MB based slices), 2 (MB row based slices) and 3 (number of slices), the driver will maintain slice count, equal to minimum of: the slice count calculated from slice mode setting and intraRefreshCnt number of slices during intra refresh period.
For NV_ENC_CONFIG_H264::sliceMode = 1 (byte based slices), the number of slices during an intra refresh wave is always 3.


For certain usecases, clients may want to avoid multiple slices in a frame. In such scenarios, clients can enable single slice intra refresh.

Query the support for single slice intra refresh for the current driver by calling the API NvEncGetEncodeCaps and checking for NV_ENC_CAPS_SINGLE_SLICE_INTRA_REFRESH.
If supported, single slice intra refresh can be enabled by setting NV_ENC_CONFIG_H264::singleSliceIntraRefresh / NV_ENC_CONFIG_HEVC::singleSliceIntraRefresh.

In case there in a resolution reconfiguration in the middle of an intra refresh wave, the ongoing wave will be terminated immediately. The next wave will start after NV_ENC_CONFIG_H264::intraRefreshPeriod number of frames.

Intra refresh is applied in encode order and only on frames which can be used as reference.
```

**Comment by MartinPulec** [comment]
Yes, but what should this be used for?

I've looked on it it in the end and unfortunately it doesn't seem to help with anything, you can check [the documentation](https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-video-encoder-api-prog-guide/#error-resiliency-features__section_klf_nr1_nlb).

Basically it looks like it allows disabling slices during intra-refresh wave - the intra-refresh setting affects slicing otherwise. We, however, want to use slices anyway so I don't think enabling this may be of any use for us.

I've also tested if it doesn't influence the problem with low-quality picture after IDR by chance but it doesn't look like to have any observable impact.

Anyways, I noticed that the new version requests quite a new driver versions so I've capped the version now to 11.0 on the contrary.

**Comment by MartinPulec** [comment]
I am thinking how to treat it further - from my point of view this option doesn't have any significant use-case for UG, from my tests there was no improvement in behavior so I don't think we will include it to upstream UG now. If you wish, I could create a side build with that either enabled or as an option for you to test. But it must be kept in mind that this also works in relation to intra-refresh and slice count options.

**Comment by alatteri** [comment]
> I am thinking how to treat it further - from my point of view this option doesn't have any significant use-case for UG, from my tests there was no improvement in behavior so I don't think we will include it to upstream UG now. If you wish, I could create a side build with that either enabled or as an option for you to test. But it must be kept in mind that this also works in relation to intra-refresh and slice count options.

Hi Martin.  No problem.  I didn't see any change in behaviour with the previous intra-refresh attempt at NVenc.  

Thanks though.

**Comment by MartinPulec** [comment]
I believe that the objective of that option is to help decoders that do not support multiple slices, since the intra refresh wave implies mutiple slices otherwise (as indicated in the [documentation](https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-video-encoder-api-prog-guide/#error-resiliency-features__section_klf_nr1_nlb) I've posted earlier). It doesn't seem to have any advantage for UG, however. FFmpeg's H.264/HEVC decoder will definitely have no problem.

It will still be possible to enable this option manually (`-c libavcodec:encoder=nvenc_hevc:single-slice-intra-refresh=1`) with up-to-date FFmpeg (but not yet in our AppImage because using older NV headers) for decoders that may not support multiple slices (arbitrary/unknown options are passed to FF codec directly), so I'd perhaps close the issue now.
