### ISSUE TITLE
Feature Request: Receiver display timeout

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#19]
Hello,

Currently when the receiver loses signal from the sender, the display is the last frame received.  I would prefer an option to goto black when signal is lost.  Either immediately, or a configurable timeout.

Thanks.

**Comment by MartinPulec** [comment]
Hi Alan,

I am not sure if you thought that it looses a signal when sender gets stopped or the sender itself looses a a signal. 

For the second option, there is an workaround now. I've just added an option "fallback" for switcher which would emulate it (a bit). Usage is a bit tricky, but might work:

    uv -t switcher:fallback -t decklink:mode=Hp24 -t \
      testcard:1920:1080:24:UYVY:pattern=blank -c libavcodec <addr>

The order of '-t' parameters is important, just briefly:
- first is a pseudocapturer allowing switching of further given devices
- by default it captures from device 0
- option ":fallback" causes that if a capture from device 0 times out, tries to
capture from second device (testcard)

The timing won't be preserved much when there is no signal from the DeckLink
but I don't think it is a problem here.

**Comment by alatteri** [comment]
Hi Martin, It's actually the first.  When the sender stops, the receiver currently holds the last frame it received.  So I was thinking this would actually be an option on the display/reciever side.  Ideally lets say receiver looses signal, there would be some option to show splashscreen/black after X number of seconds with no signal.   But the fallback option is also good, but different.  Having both options would be great.

**Comment by alatteri** [comment]
Thinking more, both these options are great.  fallback on the sender side, and blanking on the receiver side.  Would be great to have the options on both solution to either show splashscreen or black.

**Comment by MartinPulec** [comment]
Yeah, just in case it would be useful, it can be implemented there. But it won't be generic.

Just to explain why it doesn't get (easily) otherwise - the API for the displays is **pushing** the frames from network. And it is quite cumbersome to intervene of it with the timeout. But the _synchronized_ mode works slightly differently internally (while API is the same). It **pulls** the frames when needed, the controlling clock is managing actually DeckLink. Therefore I could handle the timeout in the "callback" that it periodically triggered.
