### ISSUE TITLE
Ultragrid 1.7.1 NDI issues

### ISSUE THREAD

**Issue by maybites** [CESNET/UltraGrid#207]
Hi

I am confused:

- according to the release (http://www.ultragrid.cz/news/UltraGrid-1.7-release/) 1.7.1 supports NDI, 
- according to the documentation (https://github.com/CESNET/UltraGrid/wiki/Syphon,-Spout-and-NDI) one needs to compile it oneself.
- according to my tests on OSX inside the Terminal:

```
/Applications/_Video/uv-qt.app/Contents/MacOS/uv -t ndi:help 
```

the feedback is

```
MasterPortDestroyer is armed
UltraGrid 1.7.1 (tags/v1.7.1^0 rev f4f370f6 built Dec  3 2021 07:37:19)

Display device   : none
Capture device   : ndi
Audio capture    : none
Audio playback   : none
MTU              : 1500 B
Video compression: none
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

Display initialized-none
WARNING: Selected 'ndi' capture card was not found.
Unable to open capture device: ndi
Exit
```

even though I have an NDI server running on the same machine. 

(I see the same error on windows, too).

Any hints?

**Comment by MartinPulec** [comment]
Hi @maybites,

sorry for delayed response and the confusion. The points are valid – the point is that NDI 5 is supported at the source code level but not present in regular builds. This is caused by NDI licensing policy  – GitHub perhaps doesn't [restrict SW export](https://docs.github.com/en/github/site-policy/github-and-trade-controls) as required by NDI license thus we cannot redistribute the library itself.

However, I guess that we may modify UltraGrid to dynamically open NDI library if you obtain/download and install it to your computer by yourself. Would it be possible for you?

**Comment by MartinPulec** [comment]
> That would be fantastic!

I've finally managed to make it done, it is currently in [development builds](https://github.com/CESNET/UltraGrid/releases/tag/continuous), we will perhaps release a minor update 1.7.2 with it next week as well.

**Comment by maybites** [comment]
Excellent. Works like a charm, at least on my OSX machine on which I can test right now.

And I saw you already updated the wiki with instructions.

Thank you so much for this quick fix! really appreciated it.
