### ISSUE TITLE
Maybe a dumb question.......

### ISSUE THREAD

**Issue by TheSashmo** [CESNET/UltraGrid#216]
So I highly depend on the "capture" and "display" log output to make sure that X = Y.

Meaning 150 frames captured. 150 frames played.

BUT, on the decoder side I see consistently 151 frames, but I don't see 151 frames captured.

Wouldn't this result to having an issue on the output side?

**Comment by MartinPulec** [comment]
Hi, not at all.

It is implemented that it simply checks timer and if there elapsed 5 seconds since last report, it reports FPS. Thus if it really depends if the last frame arrives in time T+5s or T+5,039s. If it occurs all the time, it is possible that the clock or receiver is slightly slower, but it even doesn't need to be the case - take in account that there is processing that introduces a bit uncertainty to this (but then it would rather oscillate between 150 and 151)

**Comment by TheSashmo** [comment]
Thanks Martin.

This opens another question.  [https://github.com/CESNET/UltraGrid/issues/212](url)

The frame count is perfect and the logs don't report anything.  But lets take the conversation over there.
