### ISSUE TITLE
[Feature Request/Question] Support for crop filter? 

### ISSUE THREAD

**Issue by Code-ScottLe** [CESNET/UltraGrid#23]
I recently stumbled across this and it has been working wonders, really appreciated the thoughtfulness behind the ease-of-use! I haven't done poking around the repo enough yet, but are there any built-in filter for cropping? Both section of capture filter + video post processing doesn't have any mention for cropping and i don't think that UltraGrid is currently using [libavfilter like ffmpeg (which has a built-in crop filter)](https://ffmpeg.org/ffmpeg-filters.html#toc-crop) 

Any help on this topic would be greatly appreciated!

**Comment by alatteri** [comment]
https://github.com/CESNET/UltraGrid/wiki/Capture-filters

**Comment by Code-ScottLe** [comment]
@alatteri I have browsed the section, but there is no mention for cropping in there. Or am i missing something here?

**Comment by MartinPulec** [comment]
Hi Scotty,
cropping is currently not implemented, however it is quite trivial to do so. Avfilter implementation would be also possible, however for this particular case it is quite unnecessary. On one hand it would give plenty of filters, on the other, I am not sure about compatibility with UltraGrid (pixel formats etc.)

Martin

**Comment by Code-ScottLe** [comment]
@MartinPulec Thanks for the answer, i do agree that bringing entire avfilterlib into UltraGrid at the moment might be overkill for just cropping ( but that might be a good one to add in the future. )

For cropping, how hard would it be for such feature to be implemented? At the moment, just being able to crop for certain region (width + heigh + Pos X + Pos Y) would be good enough for my case, but a full blown crop like what avfilter has would be awesome as well.

**Comment by MartinPulec** [comment]
@Code-ScottLe It is not hard to implement at all, just a few memcopies (it need to be only correctly aligned).

I am just unsure about your scenario – you want to display the same 540x540 on both machines or the top on one and the bottom on the other? For the second possibility, the use of reflector won't currently do the job because it cannot do the processing (only change of transmission properties like the video compression).

**Comment by Code-ScottLe** [comment]
@MartinPulec Hmm, i thought that the reflector can do capture-filter. I have 2 boxes of 540x540 video feed stacked vertically on the desktop, so when the screen recorder records this, it will record a region of 540x1080 which contains both of them. Basically i am trying to crop this single recording feed and separate them into 2 different video streaming feeds of 540x540 that can be send separately so I can re-stack them in any order for playback.

Is this even do-able in UltraGrid? `ffmpeg` can do multiple output for a single input AFAIK, but i can't find anything in the `-t help` option of UltraGrid yet.

**Comment by MartinPulec** [comment]
I see, no, this is currently not possible (actually there has been something very similar - a dual link mode that split the output to halves and sent it to different addresses, but I think it won't work for you because it expected single receiver).

However, I think there is one possibility how to do that (relatively) flawlessly – what about sending the 540x1080 picture to both machines with the reflector and using (implementing) crop as a video postprocess filter? One receiver would have vertical offset 0 and the second 540 (obviously).

**Comment by Code-ScottLe** [comment]
@MartinPulec Which is even better. I only suggest crop as Capture Filter because that is what we have currently. If we can do post processing filter, that is all for the better.

Without using UltraGrid, i was able to do the exact same thing using ffmpeg streaming over RTP multicast and using mplayer on the other end to do exactly like what you said : read the 540x1080 input twice and apply 2 crop filters to get what i need. The only reason why i am asking is because of the obvious reason : ffmpeg RTP multicast sucks major time in term of latency + usefulness compare to UltraGrid. UltraGrid Multicast is also much more stable (no smearing) compare to ffmpeg RTP for some reason...

Also, it isn't fixed to a single receiver, it would be more fluid than that. If i have 2 receivers, then each of them can be assigned either of the feed. But if i have only one, then I have option to stack them. Think of either 2 squared LCDs , or a single wide LCD :)  

It is about creating the flexibility on the playback as the sender source is unchangeable.

**Comment by MartinPulec** [comment]
Sure, in this case it should be feasible for your case. The downside of video postprocess filter is that only one can be applied (capture filters can be chained), therefore something like crop+scale would not be possible (unless it is done in one filter).

**Comment by MartinPulec** [comment]
You can try the commit 01c07eba7 (currently in my [devel](https://github.com/MartinPulec/UltraGrid) branch)? It should work although it may not handle correctly all edge cases. Would it be possible for you to compile and test it? If you need a build for Windows, I can make a build.

**Comment by Code-ScottLe** [comment]
That is quite fast! I don't have the build environment setup, can you make a build?

Thanks!

**Comment by MartinPulec** [comment]
You can try [this](https://github.com/CESNET/UltraGrid/releases/download/nightly/UltraGrid-20190626-devel-win64.zip) build. It is not a regular build, so I'll remove it later (but then the functionality will be perhaps merged to master).

**Comment by Code-ScottLe** [comment]
Just got around to try the corp filter and it is working wonders. But i am running into a weird issue (probably worth another issue up here).

If i use the reflector to send to the same device (same ip), using 2 different port (in this case, 5004 and 5005). If i were to start play back on the port with the lower number (5004), the higher port playback will be stuck at "waiting for video". If i were to reverse the playback order , start 5005 first, and then 5004, then things will be okay. Same thing with 6004 and 6005.

**Comment by MartinPulec** [comment]
Well, this is not entirely a bug, it is because according the RTP, port+1 is usually allocated for RTCP, when started UltraGrid with port 5004 it listens also on 5005 and due to a "permissive" settings on sockets (SO_REUSEADDR), it "steals" traffic from the instance that sends RTP data on 5005.

It is true that it may be confusing somehow but I think that it is the best alternative - RTCP use is more or less compulsory according to the RFC (although UG works without that - it doesn't need to be solved with reflectors). It is also possible not to use SO_REUSEADDR which would cause listening on same port number fail. But this is also less favorable because it may need to wait until socket timeouts between 2 UG runs (in case that it crashes and doesn't correctly close the socket).

**Comment by Code-ScottLe** [comment]
>Well, this is not entirely a bug, it is because according the RTP, port+1 is usually allocated for RTCP, when started UltraGrid with port 5004 it listens also on 5005 and due to a "permissive" settings on sockets (SO_REUSEADDR), it "steals" traffic from the instance that sends RTP data on 5005.

TIL, i guess i can give non port + 1 for the second feed. It is no big deal. 
[https://gfycat.com/menacingamplearcticwolf](Here is a sneak peak into what I am needing all of this odd resolution + crop solution for)

Also an odd question, if i remember correctly, SDL gives you an option to specify the window size + no border/title bar with ` SDL_NOFRAME ` , is that still something that they support / configurable for UltraGrid? (might as well be another feature request here)

**Comment by MartinPulec** [comment]
You remember correctly, it used to. But current implementation is with SDL2, which was completely rewritten and these options might have not been re-added. SDL (1) is still available but it will be needed to rebuild UG with that (SDL1 and SDL2 must not be used in one program at the same time). Feel free to open the feature request, AFAIK it may be re-added.

**Comment by Code-ScottLe** [comment]
Thanks, I have created issue #24 for SDL stuffs, we can close this one along with the PR for the crop Post-processing filter. Much appreciated! :)
