### ISSUE TITLE
fbdev or fbdev2 output

### ISSUE THREAD

**Issue by TheSashmo** [CESNET/UltraGrid#243]
I was wondering if there was any ability to add/enable fbdev/fbdev2 as a display output?  This is good when using a server based installation where it can be used in a semi headless or userless environment without the need to enable an X environment.

**Comment by alatteri** [comment]
Hi Sashmo,

I use nodm to have a display when used with Ubuntu server so no need for a full Window Manager.

**Comment by TheSashmo** [comment]
Awesome I need to google that.  Any links to share?

**Comment by alatteri** [comment]
https://github.com/spanezz/nodm

apt-get install nodm

**Comment by TheSashmo** [comment]
Cool thanks.

**Comment by MartinPulec** [comment]
AFAIK SDL1 [supported Linux framebuffer](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlenvvars.html). It can still be compiled with UltraGrid (although AppImage doesn't do so since SDL1 and SDL2 are mutually incompatible within one program). But I assume it will have a poor performance because the absence of HW acceleration even for scale. Perhaps only in emergency.

Or, as Alan said, if you are able to use X11, it is quite easy to run the server from command-line. It is also possible without a DM:

    export DISPLAY=:0
    X $DISPLAY &
    openbox &                 # WM may not be necessarily needed but I'd recommend running one for convenience
    [ start UltraGrid here ]

**Comment by TheSashmo** [comment]
Thanks I will try this out!
