### ISSUE TITLE
SVT_HEVC white point getting compressed

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#267]
Hello,

When using SVT_HEVC, the top whitepoint is getting compressed down.  The easiest way to understand this is to see the attached screencaptures from Scopebox.   I've put the same signal using x265 and then SVT_HEVC and you will see the difference.   x265 is completely accurate, SVT_HEVC the black point is anchored, but the white point is compressing down.

The following parameters where used for encode:

`UltraGrid.AppImage --tool uv -t decklink:device=0:codec=R12L -c libavcodec:encoder=libsvt_hevc -P 5004`
`UltraGrid.AppImage --tool uv -t decklink:device=0:codec=R12L -c libavcodec:encoder=libx265 -P 5004`

and on the decoder:

`uv -d decklink --param use-hw-accel,decoder-use-codec=R12L`

**768 white-**

![768_svt_hevc](https://user-images.githubusercontent.com/625982/202334728-83bcf1a8-7b99-4619-9972-6fcf20270a6e.png)
![768_x265](https://user-images.githubusercontent.com/625982/202334729-0b38445b-b222-484d-a838-a790ea18b9ed.png)

**Black to White ramp:**

![B_W_ramp_svt_hevc](https://user-images.githubusercontent.com/625982/202334768-f6efb1db-f5bc-4065-84c7-947d69ddf96e.png)
![B_W_ramp_x265](https://user-images.githubusercontent.com/625982/202334769-24f28f0b-9156-469d-ab24-b60d70c8b74b.png)

**Rainbow Pattern:**

![rainbow_svt_hevc](https://user-images.githubusercontent.com/625982/202334817-b8555d4b-79ce-4797-a710-d0cf413295c2.png)
![rainbow_x265](https://user-images.githubusercontent.com/625982/202334824-a1d7f9ea-e15f-4a52-a90c-60707b971746.png)

**1023 White**

![1023_svt_hevc](https://user-images.githubusercontent.com/625982/202335471-5c992d4d-f055-4b89-bf1c-f8535cbf55c7.png)
![1023_x265](https://user-images.githubusercontent.com/625982/202335478-757d3bd6-ceab-4458-b9d9-382b0d2edfb2.png)

**Comment by alatteri** [comment]
**256-512 ramp**

![256_512_ramp_svt_hevc](https://user-images.githubusercontent.com/625982/202335846-86dde37b-a48f-4726-a815-a2fbf71b007e.png)
![256_512_ramp_x265](https://user-images.githubusercontent.com/625982/202335848-1e5ba74e-3d4e-4cd9-b0ba-e5e24857ca3e.png)

**Comment by MartinPulec** [comment]
Hi, thanks for reporting, I'd need to have additional information. I could not reproduce it on a first try. Please see below:

    $ UltraGrid-continuous-x86_64.AppImage -t testcard:pattern=blank=0xffffff:codec=R12L:size=1024x256 \
    >  -d dummy:dump_to_file -c libavcodec:encoder=libsvt_hevc --param decoder-use-codec=R10k
    $ # wait until dummy.r10k is created
    $ tools/convert 1024 256 R10k RGBA dummy.r10k dummy.rgba
    $ convert -depth 8 -size 1024x256 dummy.rgba -resize 1x1 txt:- | tail -n 1 # eval. avg. color with ImageMagick
    0,0: (254,254,254,255)  #FEFEFEFF  srgba(254,254,254,1)

Codec for `--decoder-use-codec=R10k` can be replaced with _RGB_ to avoid the intermediate converting step, but it is less reliable because different conversion (yuv444p10le->RGB vs. yuv444p10le->R10k) is used, in the original case only the soundness of R10k->RGB is expected (which is quite trivial since it just shuffles bits).

Also do you have any idea why 768 and 1023 x265 (as well as SVT) are different? For x265, color-picker gives me `#CCCCCC` and the later`#FFFFFF`.

Is it possible to:
1. avoid using `--param use-hw-accel` -- unless the problem lies there, it adds a nondeterminism whether the acceleration is actually used and if it is, what does the HW decoder output
2. try testcard->decklink
3. similarly decklink->gl  (SDL or other "reference" display)

**Comment by alatteri** [comment]
Hi Martin... Thanks for taking a look.  I'll be traveling this week (American holiday), I try to do further testing shortly there after.  Just a tad of background.  SVT_HEVC is the only software based codec I've been able to get encoding in realtime at 4K.  I've never been able to get x265 to encode 4K@24fps.  NVENC is *NOT* an option because of the Decklink capture issue from the other thread.  #248 

A thoughts though:

Sorry, I'm not clear on the discrepancy you are highlighting.  Isn't this the problem I'm describing?  In SVT mode the white point is getting compressed down, while the black point is staying the same. In post-production we would say this is bringing the "gain" down. 
> Also do you have any idea why 768 and 1023 x265 (as well as SVT) are different? For x265, color-picker gives me #CCCCCC and the later#FFFFFF

I believe I did try it without hw-accel and the result was the same.   I do feel that UG/libavcodec is smart enough to try HW accell and then revert to software decode.  I'll test again
> avoid using --param use-hw-accel -- unless the problem lies there, it adds a nondeterminism whether the acceleration is actually used and if it is, what does the HW decoder output

This will be harder to objectively quantify the output signal values here, but I might be able to capture the HDMI output of a Intel NUC into a decklink to use the scopes
> similarly decklink->gl (SDL or other "reference" display)

**Comment by MartinPulec** [comment]
> [...]  I'll be traveling this week (American holiday), I try to do further testing shortly there after.

no problem

> Sorry, I'm not clear on the discrepancy you are highlighting

don't worry, I misunderstood that the values 768 and 1023 were white levels (well, 768 is somehow grayish)

> I believe I did try it without hw-accel and the result was the same. I do feel that UG/libavcodec is smart enough to try HW accell and then revert to software decode. I'll test again

Well, provided that the decoder isn't involved in the problem, it really shouldn't matter. The point is that if it _were_ caused by the decoder, than HW accelerated decoder obviously is completely different than SW. But it preliminary doesn't seem to be the case, but without the acceleration, the reproducibility is better.

**Comment by alatteri** [comment]
Attached are TIFs of most of the test patterns I use above.

[test_patterns.zip](https://github.com/CESNET/UltraGrid/files/10099010/test_patterns.zip)

**Comment by alatteri** [comment]
OK....I figured this out.  On my receiver I was setting the environment variable  `CFLAGS=-DYCBCR_FULL CXXFLAGS=$CFLAGS` at compile time.  Once I removed and recompile, everything works as desired and values are accurate.  Issue closed.
