### ISSUE TITLE
NVENC:  Single slice intra refresh needs SDK 11.1 at build time

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#289]
Looking at NVENC again, and I tested `single-slice-intra-refresh=1`  which reported this error:
`[lavc hevc_nvenc @ 0x7f44c850dc80] Single slice intra refresh needs SDK 11.1 at build time`

I wonder 2 things:

1.  Would single-slice-intra-refresh minimize the GOP pulse issue?
2.  Would single-slice-intra-refresh help with the software based decode performance?

Thanks.

**Comment by MartinPulec** [comment]
> 1. Would single-slice-intra-refresh minimize the GOP pulse issue?

I don't think so, see also [here](https://github.com/CESNET/UltraGrid/issues/244#issuecomment-1339513552). Actually, I don't know what is the advantage of using just one slice for refresh when otherwise the stream uses more. Maybe to slightly reduce the bandwidth, because when intraframe data transmitted during intra refresh consume more space?

> 2. Would single-slice-intra-refresh help with the software based decode performance?

Again I am now writing only with an a priori knowledge but I don't think that there is a potential. The other way round, if the decoder supports slice-based parallelism, this would perhaps hurt the performance, wouldn't it? Because during the refresh wave (which is UltraGrid set to produce continually), only one slice would be present.

Anyways, if you wish to test, I've enrolled a testing [build](https://github.com/MartinPulec/UltraGrid/actions/runs/4084467997) with current NV SDK ([here](https://owncloud.cesnet.cz/index.php/s/4dORPxmCVrbkRDz) is AppImage backup link, not sure if GH allows you download the build artifacts)

**Comment by alatteri** [comment]
You are right, I saw no difference in behavior of either of the items.

`--param lavc-rc-buffer-size-factor=0` does seem to eliminate the GOP pulse, but I think I remember there is a downside to using that too.

**Comment by MartinPulec** [comment]
>  but I think I remember there is a downside to using that too.

not sure if it is the one you have on your mind, but from UltraGrid perspective it is negative that this effectively disables an attempt to equalize frame sizes. So you don't have pulsation, but the particular IDR frames may be quite huge, meaning that you'll need multiple times the link width than nominal bitrate. Something in-between can be also chosen - if you choose "_lavc-rc-buffer-size-factor=2_", you'll need a link capacity approximately twice as much as nominal bitrate to accommodate the peaks (and it may still slightly pulsate, but less - default factor is _1_).
