### ISSUE TITLE
BMD DeckLink Ultrastudio 4K Mini latency

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#299]
Hello,

I am using a BMD DeckLink Ultrastudio 4K Mini in combination with NUC12i7 to encode using hevc_qsv.  This allows encoding of UHD with a very small footprint machine.  Two things I am noticing.

1) The screen of the BMD device indicates a 10 frame buffer.  I am wondering if this is controllable and can be reduced to achieve a lower latency?

2) The screen of the BMD device shows black during capture/encode, but when the same device is used to output/receive the signal is shown on the screen.

Thank you.

https://www.blackmagicdesign.com/products/ultrastudio/techspecs/W-DLUS-11

![IMG_1227](https://user-images.githubusercontent.com/625982/223313457-0056c13f-7c96-4588-99b9-2fecb2432620.jpeg)

**Comment by alatteri** [comment]
seems related to this in the SDK

```
— bmdDeckLinkCapturePassthroughModeDisabled
In disabled mode the video input is not displayed out the monitoring outputs, which instead display black frames or the last frame played, dependant on the configuration of the Idle Output setting (see BMDIdleVideoOutputOperation).
```

**Comment by MartinPulec** [comment]
> 1. The screen of the BMD device indicates a 10 frame buffer. I am wondering if this is controllable and can be reduced to achieve a lower latency?

If you are capturing only, I believe that this is an undefined value, it is relevant for playback only (when tested, it displays me some 119 frames, which is obviously not correct).

> 2. The screen of the BMD device shows black during capture/encode, but when the same device is used to output/receive the signal is shown on the screen.

In other words you'd like to have a passthrough enabled when capturing? It should be possible by:

    uv -t decklink:passthrough [other_opts]

(or `:passthrough=keep` to keep device defaults)

We've disabled by default because it doesn't play well with a bidirectional transmissions where automatic cutting the input to output is undesirable.

**Comment by alatteri** [comment]
perfect.  that is it.
