### ISSUE TITLE
JPEG codec clarification

### ISSUE THREAD

**Issue by lsde** [CESNET/UltraGrid#3]
Hello,
in the https://github.com/CESNET/UltraGrid/blob/master/README#L68 , there is an explicit mention of JPEG2000 compression ability, although the underlying GPUJPEG library does only DCT-based JPEG compression and not the wavelet-based JPEG2000.

Could you clarify on this, and eventually fix the readme to avoid confusion?

**Comment by MartinPulec** [comment]
Hi,

thank you for pointing this out, this information is a bit misleading 
although correct. UltraGrid itself contains really GPUJPEG, which is a 
standard JPEG CUDA-based compression algorithm. JPEG2000 is also 
supported, however is not shipped with UltraGrid since it has been 
separated as a standalone commercial product 
(http://comprimato.com/products/). This info is merely a relict from 
those times, I'll change the requirements to JPEG compression.

Let me know if you have further questions to UltraGrid/GPUJPEG/JPEG2000.


Thanks,
Martin
