### ISSUE TITLE
Native decoding on RaspberryPi 4

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#31]
RaspberryPi 4 is surprisingly powerful, and includes hardware decoding of h.264/h.265.  It would be great if UltraGrid supported the hardware codec of RaspberryPi 4 to make it a very small and cheap UG decoder device.  The HDMI out even supports HDR.

Thanks,
Alan

**Comment by MartinPulec** [comment]
Hi Alan,

have you tried the AppImage build for armhf? This is a build with the FFMPEG from Raspbian and therefore it should have the support for HW-accelerated H.264 decoding included. This only needs to be explicitly turned on, see [here](https://github.com/CESNET/UltraGrid/wiki/Device-Settings#Decoding).

This won't currently work for H.265 but there will eventually be a V4L2 API for it (see [this issue](https://github.com/raspberrypi/firmware/issues/1168)). So when the API is ready, it may be eventually supported by UltraGrid (currently there is only V4L2 capture since there haven't been a need for the playback module yet).

**Comment by alatteri** [comment]
HI Martin,

I had done my own compile of master on RPi4.  Thanks for updating the wiki, those switches will probably make it work.  I'll try to test it and other things this weekend.

**Comment by llamafilm** [comment]
It would be awesome to get HEVC playback on the Pi 4.  I know the hardware is capable.  With VLC I'm seeing smooth playback of UHD 10-bit HEVC (limited to 4:2:0) with CPU is around 30%.

I see two obstacles here.  First, I can't get UltraGrid to output anything to HDMI without X11.  It compiled with no problem (from git master), but it seems to be looking for an X server which I don't have.  Is there some way to output directly to the framebuffer?
```
[1610256935.479] [GL] failed to open display ''
```


From what I've read, the HEVC decoder uses a custom pixel format known as "sand".  To use this in ffmpeg, it has to convert to some other format which is way too slow in software.  (I see 8fps in HD).  VLC and Kodi have found a way to pass the opaque sand buffers to the HDMI output which knows how to display it.  Would this be possible to implement in UltraGrid too?

For testing, I built ffmpeg with patches by popcornmix, and UltraGrid does see the codecs but they don't work:
`H.265 - available (encoders: hevc_v4l2m2m hevc_vaapi, decoders: hevc hevc_rpi hevc_v4l2m2m)`
These two decoders don't work in ffmpeg either.  They have implemented instead as an hwaccel.  I can decode UHD 10-bit at 76fps with a command like this: `ffmpeg -hwaccel rpi -i uhd40Mb-420.ts -f vout_rpi /dev/null`

**Comment by llamafilm** [comment]
I just realized UltraGrid has some hwaccel support already, so maybe this could be implemented that way instead of waiting for v4l2 API.  What do you think @MartinPulec ?

**Comment by MartinPulec** [comment]
Hi @llamafilm,

instead of GL it may be possible to use SDL which could have a non-X11 backend for RPi?

As for the hw acceleration - yes and no, in UltraGrid currently supports only VDPAU/VAAPI, any new must be implemented. I am not sure if Raspberry is currently a priority but feel free to open a issue with a feature request.
