### ISSUE TITLE
VANC processing

### ISSUE THREAD

**Issue by TheSashmo** [CESNET/UltraGrid#315]
How does UG handle VANC in the source SDI?

**Comment by MartinPulec** [comment]
It doesn't do this in any way. What exactly would you like to transmit? Something specific or rather something like arbitrary VANC data?

**Comment by TheSashmo** [comment]
I was just curious, when the source SDI has VANC and if its processed in any way, like captions, or any SMPTE VANC Data.

 
![IMG_0868](https://github.com/CESNET/UltraGrid/assets/7197010/46e0c4b2-3779-4493-85ee-5352288a35f4)

**Comment by MartinPulec** [comment]
I understand - as I've written, it has not been handled in any way so far. Not because it were not possible but because it wasn't requested.

**Comment by TheSashmo** [comment]
I don't think its needed, but its more nice feature to have to be able to pass the VANC data in through the pipeline.

**Comment by MartinPulec** [comment]
I basically agree that it may be useful in general and I think that we may add a support in feature.

But I'd perhaps wait for an appropriate use case to see, what is supposed to be transmitted. Because depending on the actual type of data there are 2 ways how it can be handled - either it can be transmitted as a opaque uninterpreted data. But there are data that may be useful to handle more sensibly - of course audio, but I suppose also colorspace metadata; maybe even captions?

**Comment by TheSashmo** [comment]
Well, I suggest that starting with captions and timecode.

608 and 708 captions are commonly needed as part of a SDI video transmit path.  I have hardware that can generate and analyze if you would like to get access to test and validate.

Timecode would be the very next important factor.  When doing a multiple camera transmit from a site, being able to carry the timecode from the source site to the end production and being able to sync all the SDI together would be a great option.
