### ISSUE TITLE
AJA 10bit RGB capture broken

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#35]
Hello,

I am testing UV with AJA Kona3G cards.  I am sending the same 2KDCI RGB10bit signal as I have with previous Decklink tests.

It seems that UV is forcing the pixfmt to YUV and flipping the image, even though the card properly is detecting RGB.

I've tried manually setting the pixfmt flag, but anything other than YUV results in black.

I have tested another software on same machine with same signal, and it shows proper image, so the input is not the issue.

AJA 15.2 drivers.  Latest UV AppImage nightly.

See photos.

![snapshot2](https://user-images.githubusercontent.com/625982/65191057-a8acfe00-da27-11e9-89c3-bb072fa0bbe9.png)
![snapshot3](https://user-images.githubusercontent.com/625982/65191058-a8acfe00-da27-11e9-80e8-edeb34fdc97f.png)

**Comment by alatteri** [comment]
I see what the problem is.  The proper format for this with AJA is NTV_FBF_10BIT_DPX but it seems UV does not support that format.  It isn't even listed.  DPX_LE is listed as (unsupported) but that is the wrong format anyway.

![snapshot4](https://user-images.githubusercontent.com/625982/65191615-6ab0d980-da29-11e9-9c6e-6c14dc59ac67.png)

**Comment by MartinPulec** [comment]
Confirming that issue, the AJA capturer is perhaps not entirely finished in respect to non-YCbCr codecs.

**Comment by MartinPulec** [comment]
Well, I've looked into it a bit and it looks quite tricky. AJA doesn't seem to be able to detect the input signal color space (or I haven't find out how yet).

I'd like to ask two further questions - the signal is dual-link HD-SDI as the first picture indicates or the second channel there is not used (and if you remove it with the _cable_ app it works still). If it is one link 3G SDI, it is level A or B? Next - it won't probably help but for curiosity - what is that application?

Thanks,
Martin

**Comment by alatteri** [comment]
3G SDI Level B.  RGB 444 Full Range 10bit.

**Comment by MartinPulec** [comment]
Thanks, I'll need to elaborate where exactly is the RGB support available. AJA support explicit color spaces (I mean RGB or YCbCr) for HDMI inputs but I haven't found it for SDI yet.

**Comment by MartinPulec** [comment]
Hi again,

one additional question - in the above non-UltraGrid software, the software itself detects that the input is RGB? With the help of the routing I am able to capture the RGB input. It is quite impossible without that because this part is not really documented in AJA SDK documentation.

The thing that doesn't currently work is the detection of input signal color space - user must specify that explicitly. I haven't found out a way how to detect that when browsing the SDK headers so I am quite curious if it can be done.

**Comment by alatteri** [comment]
OK....I believe yes, it is manually specified in that software.

**Comment by MartinPulec** [comment]
In that case, I've pushed to the GIT the changes. Basically if you specify an RGB codec, the capture expects that the input is in RGB (and vice versa for YCbCr). However, you can _explicitly_ specify the input codec by using **RGB** or **YUV** parameter. In that case, colorspace conversion may occur (if input signal doesn't match the captured codec). See [here](../wiki/Device-Settings#RGB_over_SDI) for more detailed usage.

The change is already in the GIT and should be included in tomorrow builds. Also similar change for playback should follow in a few days.

**Comment by alatteri** [comment]
Thanks.... I'll see if I can test it later this week..might be next week though.

**Comment by alatteri** [comment]
using -t aja:codec=R10k the colors visually look correct, but the picture is upside down.
master rev 137a701

![snapshot6](https://user-images.githubusercontent.com/625982/65825145-4672ab00-e228-11e9-9efb-689f7e019d1c.png)

**Comment by MartinPulec** [comment]
Can you please provide the command that you use? I am not sure this is actually caused by the capture or compression/display.

**Comment by alatteri** [comment]
`uv -t aja:codec=R10k -d sdl`

**Comment by alatteri** [comment]
I have many extra, I can send you one if you want.

**Comment by MartinPulec** [comment]
I was not still able to reproduce the problem. What I am doing:

- testcard with the mode you described played through DeckLink 3D (it supports only 8-bit RGB but I don't think it matters since on the wire it should be 10-bit signal still)
- captured the sdi with AJA Kona 3G as you indicated but no problem when displayed with the SDL display (current AppImage)

Do you have some other ideas what can differ? Can you please do a quick check if the problem is not in SDL (eg. using testcard).

**Comment by MartinPulec** [comment]
Another idea - I am not sure how it is with SDK/driver compatibility - which driver version do you use? If other than 15.2.2.1 (current for Linux), can you try this one?

**Comment by alatteri** [comment]
15.2.0-2 as dictated by the vendor of the vfx software that generates the signal.  I'll take a look at the actual SDI signal with a monitor to make sure it is not flipped itself, which does seem unlikely.

**Comment by MartinPulec** [comment]
@alatteri thanks, I can confirm that it is not due to driver/SDK incompatibility - I've tested the AppImage with the 15.2.0.2 driver version and the picture was not flipped. Another idea, can you please try `-t aja:clear-routing:codec=R10k`? It also won't perhaps help but just to exclude this possibility.

**Comment by alatteri** [comment]
Decklink are better cards.  Closing since I dot use AJA anymore.
