### ISSUE TITLE
Video quality is corrupted on newest continues build

### ISSUE THREAD

**Issue by zbynekdrlik** [CESNET/UltraGrid#358]
Hi, as I am forced to use continues nightly build as last stable version has not working spout I see that all videos played directly in one command from ndi/spout/dishow/screen to local gl/sdl video is corrupted

![image](https://github.com/CESNET/UltraGrid/assets/26905282/4f934a56-b78b-4454-b7de-1543d0362d58)

simple eg. command : uv -t dshow:11 -d gl

**Comment by MartinPulec** [comment]
Thanks again for reporting. If you think the vertical lines (not the top/bottom-most part that may or may not be similar problem), I don't think there is the bug. It seems to me that these are just missing data. If you look at the output, there should be percent loss, something like:

    SSRC 0xe858b98b: 67872/67968 packets received (99.8588%), 96 lost, max loss 35

Ideally, there should be 100%. If you'll see a significant loss, it is partly because Windows network stack is not being capable to transmit over the localhost the uncompressed data stream – depending on your video properties it may be 1.5 Gbps (for FHD RGB) or proportionally more or less. You can look at [extending buffers](https://github.com/CESNET/UltraGrid/wiki/Extending-Network-Buffers#windows), but I am not sure if it will be possible to set on localhost in MSW. Or just use some compression, like `-c libavcodec`. Alternatively you can also avoid using the network stack for local preview with `-x V:loopback` (of course it won't be possible when really sending over a network).

>  as last stable version has not working 

Just FYI, the "scheduled" term for next bug-fix release, that should fix it, is 20th. If needed, we can emit it earlier if you wish, but I don't think that the behavior will be different from "continuous" build in this respect.

**Comment by zbynekdrlik** [comment]
This is not appearing in last stable version 1.8.6. I will also test your ideas but it is different behavior between stable and nightly.

We are still in testing phase of usage ultragrid so no critical situation. Thankful that some github project have active maintenance :)

**Comment by MartinPulec** [comment]
Seems like I am able to reproduce with `-t testcard:p -d gl`.

**Comment by zbynekdrlik** [comment]
Today I am available to do tests. As you reproduce it, is my support needed anymore?

**Comment by MartinPulec** [comment]
>  As you reproduce it, is my support needed anymore?

As for now perhaps not, I'll write back with updates.

**Comment by MartinPulec** [comment]
Should be fixed by now and the builds are rebuilt as well.

**Comment by zbynekdrlik** [comment]
Solved - working excellently 💯
