### ISSUE TITLE
removal of parameters

### ISSUE THREAD

**Issue by maybites** [CESNET/UltraGrid#394]
Hi

In one of your recent updates you removed a parameter called

`
log-nocolor
`

which was introduced due to a request of mine.

I understand your need of removing obsolete parameters - it would be nice if you would allow for a more graceful warning, like

'parameter log-nocolor is deprecated and has no effect anymore'

instead of stopping the script altogether.

I am using ultragrid with https://github.com/telemersion/telemersive-gateway and my scripts can't always keep up to all your recent changes - it would be nice if my app doesn't break because you decided to drop a parameter. This way a user can always use your latest versions and doesn't have to rely with the version I deploy with my app.

cheers

martin

**Comment by MartinPulec** [comment]
Hi, well, it is actually my fault. The parameter has just renamed to `log-color=no` in bc25340a9. The point is that the new parameter allows also setting the "positive" variant to enforce color output even when it would be disabled otherwise (eg. not a tty).

>I understand your need of removing obsolete parameters - it would be nice if you would allow for a more graceful warning, like
>
> 'parameter log-nocolor is deprecated and has no effect anymore'

Well, not really - as indicated above, the renamed parameter has still the same meaning. I don't know the context when it was added, it should not be usually required - the colors should be turned off if not supported. But of course there can be corner cases that were not considered.

>
> instead of stopping the script altogether.
> 
> I am using ultragrid with https://github.com/telemersion/telemersive-gateway and my scripts can't always keep up to all your recent changes - it would be nice if my app doesn't break because you decided to drop a parameter. This way a user can always use your latest versions and doesn't have to rely with the version I deploy with my app.

Actually I'd say that we try to keep the compatibility if possible. The point of not keeping compat it in this particular case is that `param`s [were not](https://github.com/CESNET/UltraGrid/blob/1a71edffd51aa48f979c710647b2395ffbf25466/src/host.cpp#L937) originally entirely a documented/public interface so I've thought it is not necessary. However, this isn't now entirely true - there also land options that do not belong anywhere else, as in this case.

So I've re-added the compat option but preferred is perhaps the new option, which allows both settings. I think that there can be just a single option.

Thanks for letting us know!

**Comment by maybites** [comment]
I am aware what a huge job it is to maintain such a product as ultragrid. 

Thank you for considering my imput.
