### ISSUE TITLE
NDI6 on linux not recognized by UG autogenerated.

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#398]
I am testing NDI6 on Ubuntu.  It fixes some issues with 10bit video.  But it doesn't seem to be recognized by UG autogen.

checking for Processing.NDI.Lib.h... no

administrator@:~$ ls -l /usr/local/lib/*
lrwxrwxrwx 1 administrator administrator       15 Jun 24 16:58 /usr/local/lib/libndi.so -> libndi.so.6.0.1
lrwxrwxrwx 1 administrator administrator       15 Jun 24 16:58 /usr/local/lib/libndi.so.6 -> libndi.so.6.0.1
-rwxr-xr-x 1 administrator administrator 26607936 May  6 07:00 /usr/local/lib/libndi.so.6.0.1

**Comment by alatteri** [comment]
I see what the issue is.  There are 2 different sets of instructions for Linux install in the wiki.  
This one does not have the `sudo cp -r NDI\ SDK\ for\ Linux/include/* /usr/local/include` step.
https://github.com/CESNET/UltraGrid/wiki/Syphon,-Spout-and-NDI

while this one does.

https://github.com/CESNET/UltraGrid/wiki/Compile-UltraGrid-(Source)#NDI

**Comment by MartinPulec** [comment]
I understand the point but actually there is a point - the library mentioned in the first link is needed as a **run-time** dependency. On contrary, the headers (and only the headers) are needed for compilation. 

I've slightly modified the text, cross-linked the pages and suggested to install (optionally) both libs and includes in both places. But I believe that the instructions in both places are appropriate - for compilation it is clear. The run-time instructions are, however, also required for Linux, because (compared to macOS and Win), there is no common place (macOS - `/Library/NDI ...`) or environment variable with that (_NDI\_RUNTIME\_DIR_V6_ in Windows) where to look up for the library.
