### ISSUE TITLE
Feature Request- FEC stats from the reflector

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#409]
Hello UG team,

It would be great if we could get received packet and FEC stats at the reflector level.

My workflow is below:

```
                              /-------> UG Receiver
UG Encoder ---> Reflector --> --------> UG Receiver
                              \--------> UG Receiver
```

I can get the packet/fec stats at the receiver level from the UG log, but there is no way to see the same states when looking at the `encoder-->reflector` segment.  maybe there could be a switch to enable received packet/FEC stats  with hd-rum

thank you.

**Comment by MartinPulec** [comment]
Here it depends whether you are using the `transcoding` reflector or just the packet reflector.

For the first case, it works, if you used something like:
```
hd-rum-transcode 8M 5004 -c lavc -P 6004 100::1
```

For just the packet reflector it is hardly possible, because it doesn't decode the content of the packets so it cannot be evaluated at that (network) level.

If it is really needed, there can be a workaround, let say I assign the receivers names:
```
                              /-------> receiverA
UG Encoder ---> Reflector --> --------> receiverB
                              \-------> receiverC
```

so that you can force the decoder by running following command:
```
hd-rum-transcode 8M 5004 receiverA receiverB receiverC -c none 100::1
```
(_100::/64_ is [IPv6 blackhole prefix](https://en.wikipedia.org/wiki/Black_hole_(networking)))

We may discuss this internally whether to add an option for it. Personally, I am not a big fan of it because it adds unnecessary load by requiring the full decode (which the user may not be aware of). It is true that the decode could stop before decompress there, but I don't believe that this is a systematic approach - the packet reflector simply transmits the packets at the transport layer and so doesn't print statistics related to the application layer.
