### ISSUE TITLE
Warning: FEC symbol size exceeds payload size! FEC symbol size: 2132

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#61]
Hello,

I get this warning nearly every time.  The symbol size value changes often. H.265 streams going over internet via VPN.

-f V:rs:200:240

Can you give some clarification on what this means?  Is this a bad error or just an info warning?  What is the result of streaming with this condition?

If I make the UG MTU really large (>~6000), then these warnings go away.  But the underlying ethernet network is 1500MTU, the VPN is 2800MTU.  Seems wrong to have to make the MTU so large to get FEC symbols.

Any guidance would be appreciated.

Thanks,
Alan

**Comment by MartinPulec** [comment]
This is nothing to worry about much. It just means that the error correction scheme is less efficient because one symbol (which is a block size of the encoding) needs to be transmitted with 2 packets. And if one gets lost it is effectively as if both were.

You can check [FEC Settings](../wiki/FEC-Settings).

Generally speaking, it may be worth trying also *LDGM* for higher-bandwidth streams. But I guess that for the HEVC it is just because the first frame is an excessively bigger I-frame and the rest is smaller, therefore really nothing to worry about much.

**Comment by alatteri** [comment]
Thanks for the info.  Would LDGM be applicable in 30mb h265 streams, or is that still to small of a data load?

**Comment by MartinPulec** [comment]
Hi Alan, no, it is too low bitrate for LDGM to work efficiently. I would say that the range in which both LDGM and Reed-Solomon should be considered is 50-100 Mb - for more LDGM, for less Reed-Solomon would be fine. The message is a bit misleading but it is question how to do it better.... Maybe to skip first N frames.

**Comment by alatteri** [comment]
Would not that mean every I-frame has the possibility of FEC being in-effective because payload size and packet loss?  Seems that making the MTU in UG larger to accommodate payload is better?

**Comment by MartinPulec** [comment]
> Would not that mean every I-frame has the possibility of FEC being in-effective because payload size and packet loss? 

In principle, yes. Can I ask you for the parameters you use to compress? Theoretically this can be slightly reduced by Intra Refresh. If possible, we are currently trying to rather keep frame sizes rather even. This is more network/latency friendly, so I was thinking about just a bit tweaking the compression.

> Seems that making the MTU in UG larger to accommodate payload is better?

This is certainly a working solution. However as you noticed, it is not always possible due to network limitations (or the packets get fragmented, which result to very similar situation that was on the beginning).

If this were still an issue, I'd perhaps consider removing rather the limitation to number of symbols, which then allows smaller ones. This needs however some further development - the limit is not artificial, but implied by the limitation of underlying library.

Regards,
Martin

**Comment by alatteri** [comment]
Hi Martin,

Here are my uv settings.  I've increased the redundancy in RS to help get even further protection.

`-l unlimited -m 2800 -t decklink:device=1:codec=R10K -c libavcodec:codec=H.265:bitrate=:bitrate=30M -f V:rs:180:250 -s embedded --audio-capture-format channels=8 --audio-codec=AAC:bitrate=128K -f A:mult:3 -P 6010`

Here are my reflector settings:
`hd-rum-transcode 80M 6012 -P 5006 XXX.XXX.XXX.XXX`

**Comment by MartinPulec** [comment]
Thanks, I see, this is pretty convenient. The truth is that libx265 tend to produce frames with much higher variance than lib264, even with intra-refresh, which is not so friendly for UltraGrid (or more specifically the network). I'll try to tweak the parameters a bit.
