### ISSUE TITLE
Aja device not detected (Kona 3 card)

### ISSUE THREAD

**Issue by stranger2904** [CESNET/UltraGrid#76]
Hello

Using latest git version, obtained and compiled SDK (tried 15.5.3.1 and 15.5.4.1), ultragrid compiled successfully

```
83:0c.0 Multimedia video controller: AJA Video Kona/Xena 2
	Subsystem: AJA Video Kona/Xena 2
	Flags: bus master, slow devsel, latency 64, IRQ 11, NUMA node 1
	Memory at fb000000 (64-bit, non-prefetchable) [size=8K]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at fa000000 (64-bit, non-prefetchable) [size=16M]
	Capabilities: [58] PCI-X non-bridge device
```

```
Usage:
	-t aja[[:4K][:clear-routing][:channel=<ch>][:codec=<pixfmt>][:connection=<c>][:device=<idx>][:format=<fmt>][:progressive][:RGB|:YUV]|:help] -r [embedded|AESEBU|analog]
where
	4K
		Video input is 4K.
	clear-routing
		remove all existing signal paths for device
	channel
		Channel number to use (indexed from 1). Doesn't need to be set for SDI, useful for HDMI (capture and display should have different channel numbers if both used, also other than 1 if SDI1 is in use).
	connection
		Connection can be one of: Analog1, HDMI1, HDMI2, HDMI3, HDMI4, SDI1, SDI2, SDI3, SDI4, SDI5, SDI6, SDI7, SDI8
	progressive
		Video input is progressive.
	RGB|YUV
		Set SDI video input to RGB or YCbCr explicitly. If capture pixel format is set, expect the same encoding on input. You can override this setting by specifying the signal color space explicitly by this option (see https://github.com/CESNET/UltraGrid/wiki/Device-Settings#RGB_over_SDI for details).

Available devices:
	no devices found

Exit
```

System is ubuntu 18,  aja driver is 15.5.3
Any ideas why the card is not visible in uv ?

**Comment by erichorwitz** [comment]
Have you loaded the Aja driver? the SDK does not load the driver automatically... I believe its in the compiled bin directory for the sdk. loadAja or something like that...

**Comment by MartinPulec** [comment]
As Erich said, it looks like the card either hasn't loaded driver or the driver doesn't manage the card. In the `lspci` output there should be otherwise lines like this:

            Kernel driver in use: ajantv2

The command is actually `load_ajantv2`. You can also check [this instructions](https://github.com/CESNET/UltraGrid/wiki/AJA-Setup) (which assume the use of retail drivers, however). If you wish, I'd send you instructions for SDK driver - it is not mentioned in the wiki intentionally because the guys at AJA objected that it looks like the SDK driver is required for AJA to run (instead of retail drivers).

Also there are 2 another points - firmware may need to be updated by `ntv2firmwareinstaller`. Second is that Kona 3 may or may not work - I think that it is no longer supported by SDK (which doesn't tell that it won't work).
