### ISSUE TITLE
Using CUDA for audio transmission only / `--enable-rt` / codecs / a few genereal questions

### ISSUE THREAD

**Issue by jmar83** [CESNET/UltraGrid#92]
1. Can CUDA be involved with audio transmission only? Or does it not change ther performance of it? Does it make mose sense for transmitter, receiver or both? (transmitter in office is a ultra-high performance notebook Acer Helios Predator 500 with 8-core AMD Ryzen 3.2Ghz and RX Vega 56 Graphics (supported or not by UltraGrid, if yes for audio?) and 48GB of RAM; computer in living room is a 9 yrs old all-in-one Computer with Win7 x64 Pro, and Nvidia 330M Graphics. When my research was right, the most current version driver from end of 2016 does not support CUDA and need an older on from 2014 + CUDA version 6.5. CUDA 6.5 may be downloaded in a PC and notebook version, maybe the difference are mobile version chips? e.g. my all-in-one computer also contains the 330M version, not just the 300. (?)

2. The parameter `--enable-rt` will show the help text only (equivalent to a wrong parameter or `-h` / `--help`

3. Where can i get the supported audio codecs. Do i just need to download e.g. a codec pack including encoders (like K-Lite "Mega") in 64 bits?

I would like to stream audio from one room to the other, but with my powerline adapter is, so at least it think, a "natural" latency.

but, the ping to living room (where `uv -r ... ` with 2 channels, PCM 44.1khz with WASAPI, but on on old windows 7 pro computer with 2 cores is running) is not soooo bad:

```
C:\Users\xyz>ping 192.168.254.105

Ping wird ausgeführt für 192.168.254.105 mit 32 Bytes Daten:
Antwort von 192.168.254.105: Bytes=32 Zeit=6ms TTL=126
Antwort von 192.168.254.105: Bytes=32 Zeit=3ms TTL=126
Antwort von 192.168.254.105: Bytes=32 Zeit=5ms TTL=126
Antwort von 192.168.254.105: Bytes=32 Zeit=11ms TTL=126

Ping-Statistik für 192.168.254.105:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 3ms, Maximum = 11ms, Mittelwert = 6ms
```

PLC adapters are Zyxel pla5456 with a lil bit more up-to-date AV2000 (Broadcom BCM60500) 3.x.x firmware from sineoji.com and highest priority between the 2 adapters from office to living room and as less switches as possible. Switch is a professional one HPE 2915 8G PoE Switch (J9562A) with most current firmware. 

And i use WASAPI on both computers.

Is there a chance for success or do i better give up with my project? Not just with UltraGrid, latency-free audio transport over ip is a difficult thing and powerline does not make it better! ;-)

Maybe another codec / compression algorithm than PCM makes it better? -> but it's not a bandwith problem, so hmmm...?

(an alterantive is an unidirectional connection with SPDIF on a wireless 2.4 or 5.8GHz analog AV transmitter over the yellow CVBS cinch port, no error correction but a latency nearly zero you will not hear - never ever)

Thank you for your feedbacks.

With best regards,
Jan

**Comment by MartinPulec** [comment]
Hi Jan,

1. no, CUDA is not supported for audio at all. Basically it usually doesn't make a sense to use CUDA for audio. Only scenario that comes into my mind would be perhaps some massive multi-channel setup. But even there the problem is that the codec usually doesn't have CUDA implementation (maybe the simple ones do, but it is question if it is worth to offload them on the GPU).

2. the `--enable-rt` is a compile-time parameter. It may rather not be used with _UltraGrid_ these days, however (UG is no longer designed to run with real-time priority). Can I ask where have you it seen? I'd perhaps make it clear in the documenation.

3. UltraGrid supports small subset of FFmpeg provided codecs (except of PCM, which is obviously native). You can see it by issuing `uv --audio-codec help` (I've also added a subset to our wiki main page feature listing). No codecs need to be (or can) downloaded - it is shipped with UltraGrid binary distribution (or taken from FFmpeg for source compilation).

I was not able to determine the problem from your description, however. Can you eventually write more details?

Thanks,
Martin

**Comment by jmar83** [comment]
Hi Martin

Thank you very much for your feedback! :-)

1.) Then i don't need to care about GPU-acceleration (neither in office with the high-end notebook (AMD Vega RX 56)  as a sender (`uv -s ... `) nor in the living room with the receiver (old one, Intel Core Duo with Geforce GT330M)

2.) The thing with the realtime parameter i've read on bottom of the project main page (https://github.com/CESNET/UltraGrid):

`The UltraGrid system will attempt to enable POSIX real-time scheduling to improve performance. This behaviour is disabled by default now, because it can occupy the whole system when enabled, but it can be stil enabled by '--enable-rt' configure option. If you see the message:

    WARNING: Unable to set real-time scheduling

when starting the application, this means that the operating system did not permit it to enable real-time scheduling. The application will run, but with reduced performance. The most likely reason for failure to set realtime scheduling is that the application has insufficient privilege: it should either be run by root, or be made setuid root. A similar message:

    WARNING: System does not support real-time scheduling

indicates that your operating system does not support POSIX real-time scheduling. The application will still run, but performance may be less than desired.`

I can't find any words "compile" or "compiler" - maybe it understand it not 100% because im not english. (from switzerland, swiss-german)


3.) When i run `uv --audio-codec help`, i can't see any available codecs but PCM. The system i use is Windows 10 Pro x64 with some additional updates for update 2004.


Genereal: So i said, i try to transmit audio in an adequate quality (so at least 44.1khz) and (almost) latency-free from one room to the other. And currently, with the config i wrote in the first post here, there is always a hearable delay / latency.

Would you say it's completely impossible to get a delay / latency that is (at least for the humean ear) unhearable with a powerline ethernet connection - no matter with "tuning" i try to use. (like high prioriry QOS betweet that 2 powerline adapters, add higher process priority in Windows task manager, using a "special" codec instead of PCM, change ethernet card properties in the windows device manager, using WASAPI, etc. pp.)

Maybe the powerline connection is the main problem, so all that "tuning" steps are senseless? Maybe i will never get a (for humans) unhearable latency / delay. (in that case, the reason is not your software (which seems to be "high-tech" and state-of-the-art), it's my network.

When i look what professional studios (and high end audio freaks) use, then i see products like 4-ports switches for many hunderts of euros, golden ethernet cables (less ohms = less latency i would say) etc. pp.

My current config is:

a.) i use a direct USB-audio to analog power amp in office (without any network technology)

AND 

b.) using UltraGrid over Powerline (with different tuning steps) AT THE SAME TIME for the living room audio system (so both rooms should have music at the same time! ;-))

...when i stand in the middle of the to rooms (corridor), the latency is well hearable.

Maybe my "project" with UltraGrid is not the right approach for things like that. Or is it? Or will i be never successful?


With best regards from Switzerland,
Jan

**Comment by MartinPulec** [comment]
Hi Jan,

> 2.) The thing with the realtime parameter i've read on bottom of the project main page (https://github.com/CESNET/UltraGrid):

Thanks a lot, I'll try to fix this - this is mostly obsolete and yep, you are right, it is also a bit confusing.

> 3.) When i run `uv --audio-codec help`, i can't see any available codecs but PCM. The system i use is Windows 10 Pro x64 with some additional updates for update 2004.

Thanks for the info. The problem is that the FFmpeg Windows builds we were using for the build are no longer available. It should be fixed now.

> 
> Genereal: So i said, i try to transmit audio in an adequate quality (so at least 44.1khz) and (almost) latency-free from one room to the other. And currently, with the config i wrote in the first post here, there is always a hearable delay / latency.
> 
> Would you say it's completely impossible to get a delay / latency that is (at least for the humean ear) unhearable with a powerline ethernet connection - no matter with "tuning" i try to use. (like high prioriry QOS betweet that 2 powerline adapters, add higher process priority in Windows task manager, using a "special" codec instead of PCM, change ethernet card properties in the windows device manager, using WASAPI, etc. pp.)

You can try to add a parameter `--param low-latency-audio` or `--param low-latency-audio=ultra`. UltraGrid is on one hand capable to reach quite a low latency for audio, but it usually needs some tuning.

> 
> Maybe the powerline connection is the main problem, so all that "tuning" steps are senseless? Maybe i will never get a (for humans) unhearable latency / delay. (in that case, the reason is not your software (which seems to be "high-tech" and state-of-the-art), it's my network.

Well, the audio and especially low-latency audio is an ongoing effort for UltraGrid, it may not yet be 100% since UltraGrid has started as a video-only project.

You can also look at projects like _JackTrip_ or _LoLa_ (from GARR).

> 
> ...when i stand in the middle of the to rooms (corridor), the latency is well hearable.
> 
> Maybe my "project" with UltraGrid is not the right approach for things like that. Or is it? Or will i be never successful?

I cannot say right now, it also depends which latency is acceptable for you - if something like 10-20 ms is OK, I think that it would be quite achievable with UltraGrid. If you are targeting less than 10 ms, you may also try out one of the above mentioned SW.

With kindest regards from the Czech Republic,
Martin

**Comment by jmar83** [comment]
Hi Martin

Thank you very very much for your feedback!

With kind regards,
Jan
